// ─────────────────────────────────────────────
// SITE CONTENT — Edit via /admin or directly
// This file is auto-generated by Decap CMS
// or can be edited manually.
// ─────────────────────────────────────────────

window.SITE_CONTENT = {

  hero: {
    tagline: "Senior UX Designer",
    headline: "I design systems that simplify <em>complex, real-world problems</em> at global scale.",
    subheadline: "Senior UX Designer at Amazon with ~20 years of experience across enterprise platforms and customer-facing products used by millions worldwide.",
    intro: "My work focuses on transforming complex workflows into intuitive, human-centered experiences. I've spent over a decade at Amazon designing systems across delivery, logistics, and financial platforms.",
    stats: [
      { num: "20",  label: "Years experience" },
      { num: "13+", label: "Years at Amazon" },
      { num: "M+",  label: "Users impacted" },
      { num: "∞",   label: "Patents filed" }
    ]
  },

  caseStudies: [
    {
      num: "01",
      title: "Amazon Locker Redirect",
      description: "Reducing missed deliveries through a seamless recovery experience across physical and digital touchpoints.",
      tags: ["Logistics", "Service Design", "Customer Experience"],
      image: "",
      url: "#"
    },
    {
      num: "02",
      title: "Amazon Locker Accessibility",
      description: "Designing inclusive pickup experiences for customers with disabilities across physical kiosks and digital interfaces.",
      tags: ["Accessibility", "Inclusive Design", "Hardware + Software"],
      image: "",
      url: "#"
    },
    {
      num: "03",
      title: "FLASH Financial Platform",
      description: "Simplifying complex financial workflows for Amazon's transportation systems used by business, accounting, and engineering teams.",
      tags: ["Enterprise UX", "Finance", "Internal Tools"],
      image: "",
      url: "#"
    }
  ],

  about: {
    paragraphs: [
      "I'm a UX designer with nearly two decades of experience designing enterprise platforms and large-scale customer experiences. My work focuses on simplifying complex systems, aligning business and technology goals, and creating intuitive, scalable solutions.",
      "At Amazon, I've spent over 13 years designing both customer-facing and internal products — from Amazon Lockers and Pickup to FLASH, Amazon's financial ledger and accounting systems hub.",
      "Before Amazon, I worked at SAP designing enterprise products and conducted international usability research across Europe. I hold a Master's in Design from IIT Bombay and am an inventor on multiple patents related to user interfaces and data visualization.",
      "Outside of work, I enjoy photography, filmmaking, and visual storytelling."
    ],
    roles: [
      { company: "Amazon", title: "Lead UX Designer — FLASH Financial Platform", duration: "Current" },
      { company: "Amazon", title: "Lead UX Designer — Lockers & Pickup",         duration: "13+ yrs" },
      { company: "SAP",    title: "UX Designer — Enterprise Products",            duration: "Pre-2012" }
    ],
    education: [
      { degree: "M.Des — Industrial Design",   school: "IIT Bombay, Industrial Design Centre" },
      { degree: "B.E. — Computer Engineering", school: "Bharati Vidyapeeth College of Engineering" }
    ]
  },

  principles: [
    {
      title: "Design for complexity",
      description: "Real-world systems are complex — good design makes them understandable without hiding the truth."
    },
    {
      title: "Systems over screens",
      description: "Great experiences span multiple touchpoints, not just interfaces. Think in services, not just pages."
    },
    {
      title: "User insight drives decisions",
      description: "Research and usability testing are central to every meaningful design decision I make."
    },
    {
      title: "Clarity over cleverness",
      description: "Simple, clear experiences scale better and serve more people than clever ones."
    }
  ],

  contact: {
    email: "nishantghadge@gmail.com",
    location: "Seattle, WA",
    status: "Senior UX Designer at Amazon"
  }

};
